CREATE TABLE tbl_users(
USERNAME	VARCHAR2(20 BYTE)
PASSWORD	NVARCHAR2(125 CHAR)
EMAIL	VARCHAR2(125 BYTE)
NAME	NVARCHAR2(125 CHAR)
NICKNAME	NVARCHAR2(125 CHAR)
ROLE	VARCHAR2(5 BYTE)
);
CREATE TABLE tbl_users (
    username VARCHAR2(20)  PRIMARY KEY,
     password nVARCHAR2(125) NOT NULL,	
    email VARCHAR2(125) ,	
    name nVARCHAR2(125),	
    nickname nVARCHAR2(125),		
    role VARCHAR2(5)
);
SELECT * FROM tbl_users;
COMMIT;